./function.sh test_router
./function.sh test_validator
./function.sh test_isms
./function.sh test_mailbox
./function.sh test_igps
./function.sh test_router
./function.sh test_examples
./function.sh test_token
./function.sh test_library
